Resources:
  TwitterLayer74F1874E:
    Type: AWS::Lambda::LayerVersion
    Properties:
      Content:
        S3Bucket:
          Ref: AssetParameters5b980c3a65c1a797109094d3326214d38b23bf416049d4bdc07b64c255980690S3BucketA9EEE905
        S3Key:
          Fn::Join:
            - ""
            - - Fn::Select:
                  - 0
                  - Fn::Split:
                      - "||"
                      - Ref: AssetParameters5b980c3a65c1a797109094d3326214d38b23bf416049d4bdc07b64c255980690S3VersionKey784D95A9
              - Fn::Select:
                  - 1
                  - Fn::Split:
                      - "||"
                      - Ref: AssetParameters5b980c3a65c1a797109094d3326214d38b23bf416049d4bdc07b64c255980690S3VersionKey784D95A9
      CompatibleRuntimes:
        - python3.7
    Metadata:
      aws:cdk:path: twitter-blog/TwitterLayer/Resource
      aws:asset:path: asset.5b980c3a65c1a797109094d3326214d38b23bf416049d4bdc07b64c255980690
      aws:asset:property: Content
  RequestsLayer58858B55:
    Type: AWS::Lambda::LayerVersion
    Properties:
      Content:
        S3Bucket:
          Ref: AssetParameters39463e419c48aa5fa2bae4b6f5966635993b4401863b1471988c9563ff21629eS3Bucket1E438C78
        S3Key:
          Fn::Join:
            - ""
            - - Fn::Select:
                  - 0
                  - Fn::Split:
                      - "||"
                      - Ref: AssetParameters39463e419c48aa5fa2bae4b6f5966635993b4401863b1471988c9563ff21629eS3VersionKey875B3C72
              - Fn::Select:
                  - 1
                  - Fn::Split:
                      - "||"
                      - Ref: AssetParameters39463e419c48aa5fa2bae4b6f5966635993b4401863b1471988c9563ff21629eS3VersionKey875B3C72
      CompatibleRuntimes:
        - python3.7
    Metadata:
      aws:cdk:path: twitter-blog/RequestsLayer/Resource
      aws:asset:path: asset.39463e419c48aa5fa2bae4b6f5966635993b4401863b1471988c9563ff21629e
      aws:asset:property: Content
  Bs4Layer76432D0D:
    Type: AWS::Lambda::LayerVersion
    Properties:
      Content:
        S3Bucket:
          Ref: AssetParameters91e886557203c9323e6f3ba36730fa8a9771a92d5d47b1169ba7cad1200f0ba3S3BucketF6034148
        S3Key:
          Fn::Join:
            - ""
            - - Fn::Select:
                  - 0
                  - Fn::Split:
                      - "||"
                      - Ref: AssetParameters91e886557203c9323e6f3ba36730fa8a9771a92d5d47b1169ba7cad1200f0ba3S3VersionKey887392C0
              - Fn::Select:
                  - 1
                  - Fn::Split:
                      - "||"
                      - Ref: AssetParameters91e886557203c9323e6f3ba36730fa8a9771a92d5d47b1169ba7cad1200f0ba3S3VersionKey887392C0
      CompatibleRuntimes:
        - python3.7
    Metadata:
      aws:cdk:path: twitter-blog/Bs4Layer/Resource
      aws:asset:path: asset.91e886557203c9323e6f3ba36730fa8a9771a92d5d47b1169ba7cad1200f0ba3
      aws:asset:property: Content
  TweetHandlerServiceRoleCFF5A352:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Action: sts:AssumeRole
            Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
        Version: "2012-10-17"
      ManagedPolicyArns:
        - Fn::Join:
            - ""
            - - "arn:"
              - Ref: AWS::Partition
              - :iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
    Metadata:
      aws:cdk:path: twitter-blog/TweetHandler/ServiceRole/Resource
  TweetHandlerServiceRoleDefaultPolicy55A3253F:
    Type: AWS::IAM::Policy
    Properties:
      PolicyDocument:
        Statement:
          - Action:
              - ssm:GetParameters
              - logs:CreateLogGroup
              - logs:CreateLogStream
              - logs:PutLogEvents
            Effect: Allow
            Resource: "*"
        Version: "2012-10-17"
      PolicyName: TweetHandlerServiceRoleDefaultPolicy55A3253F
      Roles:
        - Ref: TweetHandlerServiceRoleCFF5A352
    Metadata:
      aws:cdk:path: twitter-blog/TweetHandler/ServiceRole/DefaultPolicy/Resource
  TweetHandlerB094FA8A:
    Type: AWS::Lambda::Function
    Properties:
      Code:
        S3Bucket:
          Ref: AssetParameters5135ec3f0c0a311a7888f9810adbdce65659bf08608c761d3bc96017d24267e5S3Bucket732E3E24
        S3Key:
          Fn::Join:
            - ""
            - - Fn::Select:
                  - 0
                  - Fn::Split:
                      - "||"
                      - Ref: AssetParameters5135ec3f0c0a311a7888f9810adbdce65659bf08608c761d3bc96017d24267e5S3VersionKeyCCCDE169
              - Fn::Select:
                  - 1
                  - Fn::Split:
                      - "||"
                      - Ref: AssetParameters5135ec3f0c0a311a7888f9810adbdce65659bf08608c761d3bc96017d24267e5S3VersionKeyCCCDE169
      Handler: handler.main
      Role:
        Fn::GetAtt:
          - TweetHandlerServiceRoleCFF5A352
          - Arn
      Runtime: python3.7
      Layers:
        - Ref: TwitterLayer74F1874E
        - Ref: RequestsLayer58858B55
        - Ref: Bs4Layer76432D0D
      Timeout: 300
    DependsOn:
      - TweetHandlerServiceRoleDefaultPolicy55A3253F
      - TweetHandlerServiceRoleCFF5A352
    Metadata:
      aws:cdk:path: twitter-blog/TweetHandler/Resource
      aws:asset:path: asset.5135ec3f0c0a311a7888f9810adbdce65659bf08608c761d3bc96017d24267e5
      aws:asset:property: Code
  TweetHandlerAllowEventRuletwitterblogRuleE969592A6C52090D:
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:InvokeFunction
      FunctionName:
        Fn::GetAtt:
          - TweetHandlerB094FA8A
          - Arn
      Principal: events.amazonaws.com
      SourceArn:
        Fn::GetAtt:
          - Rule4C995B7F
          - Arn
    Metadata:
      aws:cdk:path: twitter-blog/TweetHandler/AllowEventRuletwitterblogRuleE969592A
  Rule4C995B7F:
    Type: AWS::Events::Rule
    Properties:
      ScheduleExpression: cron(0 18 ? * FRI *)
      State: ENABLED
      Targets:
        - Arn:
            Fn::GetAtt:
              - TweetHandlerB094FA8A
              - Arn
          Id: Target0
    Metadata:
      aws:cdk:path: twitter-blog/Rule/Resource
  CDKMetadata:
    Type: AWS::CDK::Metadata
    Properties:
      Modules: aws-cdk=1.22.0,@aws-cdk/assets=1.22.0,@aws-cdk/aws-apigateway=1.22.0,@aws-cdk/aws-applicationautoscaling=1.22.0,@aws-cdk/aws-autoscaling=1.22.0,@aws-cdk/aws-autoscaling-common=1.22.0,@aws-cdk/aws-autoscaling-hooktargets=1.22.0,@aws-cdk/aws-certificatemanager=1.22.0,@aws-cdk/aws-cloudformation=1.22.0,@aws-cdk/aws-cloudfront=1.22.0,@aws-cdk/aws-cloudwatch=1.22.0,@aws-cdk/aws-codebuild=1.22.0,@aws-cdk/aws-codecommit=1.22.0,@aws-cdk/aws-codepipeline=1.22.0,@aws-cdk/aws-ec2=1.22.0,@aws-cdk/aws-ecr=1.22.0,@aws-cdk/aws-ecr-assets=1.22.0,@aws-cdk/aws-ecs=1.22.0,@aws-cdk/aws-elasticloadbalancing=1.22.0,@aws-cdk/aws-elasticloadbalancingv2=1.22.0,@aws-cdk/aws-events=1.22.0,@aws-cdk/aws-events-targets=1.22.0,@aws-cdk/aws-iam=1.22.0,@aws-cdk/aws-kms=1.22.0,@aws-cdk/aws-lambda=1.22.0,@aws-cdk/aws-logs=1.22.0,@aws-cdk/aws-route53=1.22.0,@aws-cdk/aws-route53-targets=1.22.0,@aws-cdk/aws-s3=1.22.0,@aws-cdk/aws-s3-assets=1.22.0,@aws-cdk/aws-sam=1.22.0,@aws-cdk/aws-secretsmanager=1.22.0,@aws-cdk/aws-servicediscovery=1.22.0,@aws-cdk/aws-sns=1.22.0,@aws-cdk/aws-sns-subscriptions=1.22.0,@aws-cdk/aws-sqs=1.22.0,@aws-cdk/aws-ssm=1.22.0,@aws-cdk/aws-stepfunctions=1.22.0,@aws-cdk/core=1.22.0,@aws-cdk/cx-api=1.22.0,@aws-cdk/region-info=1.22.0,jsii-runtime=Python/3.8.1
    Condition: CDKMetadataAvailable
Parameters:
  AssetParameters5b980c3a65c1a797109094d3326214d38b23bf416049d4bdc07b64c255980690S3BucketA9EEE905:
    Type: String
    Description: S3 bucket for asset "5b980c3a65c1a797109094d3326214d38b23bf416049d4bdc07b64c255980690"
  AssetParameters5b980c3a65c1a797109094d3326214d38b23bf416049d4bdc07b64c255980690S3VersionKey784D95A9:
    Type: String
    Description: S3 key for asset version "5b980c3a65c1a797109094d3326214d38b23bf416049d4bdc07b64c255980690"
  AssetParameters5b980c3a65c1a797109094d3326214d38b23bf416049d4bdc07b64c255980690ArtifactHashBE82EFEB:
    Type: String
    Description: Artifact hash for asset "5b980c3a65c1a797109094d3326214d38b23bf416049d4bdc07b64c255980690"
  AssetParameters39463e419c48aa5fa2bae4b6f5966635993b4401863b1471988c9563ff21629eS3Bucket1E438C78:
    Type: String
    Description: S3 bucket for asset "39463e419c48aa5fa2bae4b6f5966635993b4401863b1471988c9563ff21629e"
  AssetParameters39463e419c48aa5fa2bae4b6f5966635993b4401863b1471988c9563ff21629eS3VersionKey875B3C72:
    Type: String
    Description: S3 key for asset version "39463e419c48aa5fa2bae4b6f5966635993b4401863b1471988c9563ff21629e"
  AssetParameters39463e419c48aa5fa2bae4b6f5966635993b4401863b1471988c9563ff21629eArtifactHash36DBEE12:
    Type: String
    Description: Artifact hash for asset "39463e419c48aa5fa2bae4b6f5966635993b4401863b1471988c9563ff21629e"
  AssetParameters91e886557203c9323e6f3ba36730fa8a9771a92d5d47b1169ba7cad1200f0ba3S3BucketF6034148:
    Type: String
    Description: S3 bucket for asset "91e886557203c9323e6f3ba36730fa8a9771a92d5d47b1169ba7cad1200f0ba3"
  AssetParameters91e886557203c9323e6f3ba36730fa8a9771a92d5d47b1169ba7cad1200f0ba3S3VersionKey887392C0:
    Type: String
    Description: S3 key for asset version "91e886557203c9323e6f3ba36730fa8a9771a92d5d47b1169ba7cad1200f0ba3"
  AssetParameters91e886557203c9323e6f3ba36730fa8a9771a92d5d47b1169ba7cad1200f0ba3ArtifactHashDD1D6983:
    Type: String
    Description: Artifact hash for asset "91e886557203c9323e6f3ba36730fa8a9771a92d5d47b1169ba7cad1200f0ba3"
  AssetParameters5135ec3f0c0a311a7888f9810adbdce65659bf08608c761d3bc96017d24267e5S3Bucket732E3E24:
    Type: String
    Description: S3 bucket for asset "5135ec3f0c0a311a7888f9810adbdce65659bf08608c761d3bc96017d24267e5"
  AssetParameters5135ec3f0c0a311a7888f9810adbdce65659bf08608c761d3bc96017d24267e5S3VersionKeyCCCDE169:
    Type: String
    Description: S3 key for asset version "5135ec3f0c0a311a7888f9810adbdce65659bf08608c761d3bc96017d24267e5"
  AssetParameters5135ec3f0c0a311a7888f9810adbdce65659bf08608c761d3bc96017d24267e5ArtifactHash628069F6:
    Type: String
    Description: Artifact hash for asset "5135ec3f0c0a311a7888f9810adbdce65659bf08608c761d3bc96017d24267e5"
Conditions:
  CDKMetadataAvailable:
    Fn::Or:
      - Fn::Or:
          - Fn::Equals:
              - Ref: AWS::Region
              - ap-east-1
          - Fn::Equals:
              - Ref: AWS::Region
              - ap-northeast-1
          - Fn::Equals:
              - Ref: AWS::Region
              - ap-northeast-2
          - Fn::Equals:
              - Ref: AWS::Region
              - ap-south-1
          - Fn::Equals:
              - Ref: AWS::Region
              - ap-southeast-1
          - Fn::Equals:
              - Ref: AWS::Region
              - ap-southeast-2
          - Fn::Equals:
              - Ref: AWS::Region
              - ca-central-1
          - Fn::Equals:
              - Ref: AWS::Region
              - cn-north-1
          - Fn::Equals:
              - Ref: AWS::Region
              - cn-northwest-1
          - Fn::Equals:
              - Ref: AWS::Region
              - eu-central-1
      - Fn::Or:
          - Fn::Equals:
              - Ref: AWS::Region
              - eu-north-1
          - Fn::Equals:
              - Ref: AWS::Region
              - eu-west-1
          - Fn::Equals:
              - Ref: AWS::Region
              - eu-west-2
          - Fn::Equals:
              - Ref: AWS::Region
              - eu-west-3
          - Fn::Equals:
              - Ref: AWS::Region
              - me-south-1
          - Fn::Equals:
              - Ref: AWS::Region
              - sa-east-1
          - Fn::Equals:
              - Ref: AWS::Region
              - us-east-1
          - Fn::Equals:
              - Ref: AWS::Region
              - us-east-2
          - Fn::Equals:
              - Ref: AWS::Region
              - us-west-1
          - Fn::Equals:
              - Ref: AWS::Region
              - us-west-2

